添加 phpmd, 修改文件复合 phpmd 检测

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -6,9 +6,11 @@ YELLOW='\033[33m'
 WHITE='\033[37m'
 NORMAL='\033[0m'
 
+phpfpmContainerName='marmot-phpfpm'
+
 # 运行格式检查
 echo -e "code style check: ${YELLOW}start${NORMAL}"
-docker exec marmot-phpfpm vendor/bin/phpcs
+docker exec $phpfpmContainerName vendor/bin/phpcs
 
 if [ $? -ne 0 ]
 then 
@@ -19,7 +21,7 @@ echo -e "code style check: ${GREEN}success${NORMAL}"
 
 # 运行重复代码检查
 echo -e "php copy paste detect: ${YELLOW}start${NORMAL}"
-docker exec marmot-phpfpm vendor/bin/phpcpd ./Application
+docker exec $phpfpmContainerName vendor/bin/phpcpd ./Application
 
 if [ $? -ne 0 ]
 then
@@ -28,9 +30,20 @@ then
 fi
 echo -e "php copy paste detect: ${GREEN}success${NORMAL}"
 
+# 运行复杂度检测
+echo -e "mess detect: ${YELLOW}start${NORMAL}"
+docker exec $phpfpmContainerName vendor/bin/phpmd ./Application text ruleset.xml
+
+if [ $? -ne 0 ]
+then 
+  echo -e "mess detect: ${RED}fail${NORMAL}"
+  exit 1
+fi
+echo -e "mess detect: ${GREEN}success${NORMAL}"
+
 # 运行单元测试检查 
 echo -e "unit test: ${YELLOW}start${NORMAL}"
-docker exec marmot-phpfpm vendor/bin/phpunit
+docker exec $phpfpmContainerName vendor/bin/phpunit
 
 if [ $? -ne 0 ]
 then 
diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,29 +1,9 @@
 #!/bin/sh
 
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local sha1> <remote ref> <remote sha1>
-#
-# This sample shows how to prevent push of commits where the log message starts
-# with "WIP" (work in progress).
-
-remote="$1"
-url="$2"
-
-echo $remote
-
-echo $url
-
-exit 1
+if [ $(expr `cat VERSION` \> $(ls Docs/version/*.md | awk -F '\/' '{print $3}' | sed -n 's/.md//p' | sort -r | sed -n 1p)) -ne 0 ]
+then
+	echo 'push fail, VERSION file different with latest version log'
+	exit 1
+else
+	echo 'push check version ok'
+fi
